"""addTestdesc

Revision ID: 3b15e0531f1c
Revises: 5eed8b284eb8
Create Date: 2024-02-27 16:57:57.252178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b15e0531f1c'
down_revision = '5eed8b284eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Test', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
